[starnet]
    minimum_time_python_skip    = 5
    region_log_file             = /work2/11056/zwu/frontera/enzo_gh/data/251110/ic512_b_starnetlibyt/starnet_insitu_logs/StarNetEvents.log
    simulation_top_dimensions   = 512
    # default 64, not used anywhere
    minimum_level_for_tiling    = 3
    # plotting is slow, only use all plots for debugging
    plot_all_images             = false
    plot_positive_images        = true
[starfind]
    stage1_model                = smalldense
    stage2_model                = incepunet
    scale_file                  = /work2/11056/zwu/frontera/enzo_gh/data/251110/ic512_b_starnetlibyt/resources/Scaling_64x160.torch
    region_dims                 = 64
    # kpc
    region_width                = 10
    # pc
    region_target_dx            = 160 
    field_list                  = density,H2_p0_density,velocity_divergence,metals,total_energy
    maximum_refinement_level    = 6
[s1_config]
    output_channels             = 2
    multi_gpu                   = true
    # only include input fields for s1
    checkpoint_path             = /work2/11056/zwu/frontera/enzo_gh/data/251110/ic512_b_starnetlibyt/model_checkpoints
    first_layer_channels        = 32
    class_weight                = 1, 4
    dropout                     = true
    p_dropout                   = 0.0
[s2_config]
    output_channels             = 2
    multi_gpu                   = true
    checkpoint_path             = /work2/11056/zwu/frontera/enzo_gh/data/251110/ic512_b_starnetlibyt/model_checkpoints
    first_layer_channels        = 4
    class_weight                = 1, 9
    dropout                     = false
    p_dropout                   = 0.0
    network_skips               = true
[fbnet]
    method = uniform_sphere
    model_time = 16
    # decides which regression_weights to use. 8 or 16 are the defaults
    # in Myr, this is the end time of stellar + SNe evolution
    model_dt = 6
    # no change
    predict_fields = p3_metallicity_radius
    neutral_fraction = 1.0
    # should be the same as MaximumRefinementLevel in .enzo or redshift restart file
    simulation_max_level = 5
    # 0.4
    radius_modifier = 0.4